services:
  - type: web
    name: my-backend-service
    env: node
    plan: free
    buildCommand: "npm install && npm install -g nodemon"
    startCommand: "nodemon index.js"
    envVars:
      - key: NODE_ENV
        value: production
